#!/bin env python3

from sqlalchemy import create_engine
from sqlalchemy.pool import QueuePool

from iam.pgiam import Db

user = 'tsd_backend_utv_user'
pw = ''
host = 'localhost'
db = 'tsd_idp'
dburi = ''.join(['postgresql://', user, ':', pw, '@', host, ':5432/', db])
engine = create_engine(dburi, poolclass=QueuePool)
db = Db(engine)
print(db.exec_sql('select * from persons', {}))
print(db.group_members('p11-export-group'))
print(type(db.persons))
print(type(db.users))